// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebCongNghe.Data;

#nullable disable

namespace WebCongNghe.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260529075640_SeedCatalogProductsByCategory")]
    partial class SeedCatalogProductsByCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebCongNghe.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Phu kien"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dien thoai"
                        });
                });

            modelBuilder.Entity("WebCongNghe.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            CategoryId = 1,
                            Description = "Laptop gaming cau hinh cao, phu hop demo danh muc laptop hieu nang.",
                            ImageUrl = "/images/sample/laptop-gaming-asus-rog.png",
                            Name = "Laptop Gaming ASUS ROG",
                            Price = 32990000m
                        },
                        new
                        {
                            Id = 1002,
                            CategoryId = 1,
                            Description = "Laptop nhe, thiet ke gon va phu hop nhom nguoi dung van phong, hoc tap.",
                            ImageUrl = "/images/sample/macbook-air-m3.png",
                            Name = "MacBook Air M3",
                            Price = 28990000m
                        },
                        new
                        {
                            Id = 1008,
                            CategoryId = 1,
                            Description = "Laptop man hinh OLED cao cap, phu hop doanh nhan va nha sang tao can hieu nang on dinh.",
                            ImageUrl = "/images/1.png",
                            Name = "Dell XPS 15 OLED",
                            Price = 45500000m
                        },
                        new
                        {
                            Id = 1009,
                            CategoryId = 1,
                            Description = "ThinkPad mong nhe, ben bi, phu hop moi truong van phong va quan ly du an di dong.",
                            ImageUrl = "/images/unnamed (2).png",
                            Name = "Lenovo ThinkPad X1 Carbon Gen 11",
                            Price = 39900000m
                        },
                        new
                        {
                            Id = 1010,
                            CategoryId = 1,
                            Description = "Laptop cao cap thiet ke linh hoat, man hinh dep va phu hop nhu cau hoc tap, thuyet trinh, sang tao.",
                            ImageUrl = "/images/unnamed (31).png",
                            Name = "HP Spectre x360 14",
                            Price = 36990000m
                        },
                        new
                        {
                            Id = 1011,
                            CategoryId = 1,
                            Description = "Thiet bi 2-trong-1 gon nhe, ket hop ban phim roi de phuc vu hoc tap, ghi chu va lam viec co dong.",
                            ImageUrl = "/images/unnamed (35).png",
                            Name = "Surface Pro 9 Keyboard Bundle",
                            Price = 31990000m
                        },
                        new
                        {
                            Id = 1003,
                            CategoryId = 3,
                            Description = "Dien thoai cao cap voi camera dep va giao dien hien dai cho demo.",
                            ImageUrl = "/images/sample/iphone-15.png",
                            Name = "iPhone 15",
                            Price = 21990000m
                        },
                        new
                        {
                            Id = 1004,
                            CategoryId = 3,
                            Description = "Dien thoai Android flagship, phu hop de demo nhom san pham di dong.",
                            ImageUrl = "/images/sample/samsung-galaxy-s24.png",
                            Name = "Samsung Galaxy S24",
                            Price = 20990000m
                        },
                        new
                        {
                            Id = 1007,
                            CategoryId = 3,
                            Description = "Phien ban cao cap voi cum camera lon, phu hop demo nhom dien thoai flagship cua Apple.",
                            ImageUrl = "/images/494a097644004c28a34bed10ae03a4ec.png",
                            Name = "iPhone 15 Pro Max",
                            Price = 29990000m
                        },
                        new
                        {
                            Id = 1016,
                            CategoryId = 3,
                            Description = "Dien thoai man hinh lon, camera nhieu ong kinh va hieu nang cao cho nhom nguoi dung nang dong.",
                            ImageUrl = "/images/unnamed (24).png",
                            Name = "Xiaomi 14 Ultra",
                            Price = 25990000m
                        },
                        new
                        {
                            Id = 1017,
                            CategoryId = 3,
                            Description = "Dien thoai thiet ke bat mat, man hinh sang va phu hop nhu cau chup anh, giai tri hang ngay.",
                            ImageUrl = "/images/unnamed (25).png",
                            Name = "OPPO Reno11 Pro",
                            Price = 16990000m
                        },
                        new
                        {
                            Id = 1018,
                            CategoryId = 3,
                            Description = "Flagship Android giao dien sach, camera thong minh va trai nghiem phan mem muot ma.",
                            ImageUrl = "/images/unnamed (26).png",
                            Name = "Google Pixel 8 Pro",
                            Price = 23990000m
                        },
                        new
                        {
                            Id = 1005,
                            CategoryId = 2,
                            Description = "Chuot khong day cao cap, thao tac tot cho nhu cau van phong va sang tao.",
                            ImageUrl = "/images/sample/logitech-mx-master.png",
                            Name = "Chuot Logitech MX Master",
                            Price = 2490000m
                        },
                        new
                        {
                            Id = 1006,
                            CategoryId = 2,
                            Description = "Ban phim co ket noi da che do, hop voi bo san pham phu kien may tinh.",
                            ImageUrl = "/images/sample/keychron-keyboard.png",
                            Name = "Ban phim co Keychron",
                            Price = 2790000m
                        },
                        new
                        {
                            Id = 1012,
                            CategoryId = 2,
                            Description = "Tai nghe over-ear chong on tot, hop cho nguoi dung di chuyen nhieu va can su tap trung.",
                            ImageUrl = "/images/70a9f09bf5634f80a9578de40ac7fa77.png",
                            Name = "Tai nghe Sony WH-1000XM5",
                            Price = 7990000m
                        },
                        new
                        {
                            Id = 1013,
                            CategoryId = 2,
                            Description = "Chuot gaming do tre thap, form gon va phu hop setup hieu nang cao.",
                            ImageUrl = "/images/b08427a925554faeb29c454a04004dc2.png",
                            Name = "Chuot gaming Razer Cobra Pro",
                            Price = 3290000m
                        },
                        new
                        {
                            Id = 1014,
                            CategoryId = 2,
                            Description = "Cu sac cong suat lon di kem cap boc du, phu hop laptop, tablet va dien thoai dong cong suat cao.",
                            ImageUrl = "/images/unnamed (22).png",
                            Name = "Bo sac nhanh USB-C 100W",
                            Price = 1190000m
                        },
                        new
                        {
                            Id = 1015,
                            CategoryId = 2,
                            Description = "Tai nghe khong day thiet ke toi gian, am thanh can bang va phu hop cho game thu, streamer.",
                            ImageUrl = "/images/unnamed (11).png",
                            Name = "Tai nghe SteelSeries Nova",
                            Price = 4590000m
                        });
                });

            modelBuilder.Entity("WebCongNghe.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 2001,
                            ProductId = 1001,
                            Url = "/images/sample/laptop-gaming-asus-rog.png"
                        },
                        new
                        {
                            Id = 2002,
                            ProductId = 1002,
                            Url = "/images/sample/macbook-air-m3.png"
                        },
                        new
                        {
                            Id = 2003,
                            ProductId = 1003,
                            Url = "/images/sample/iphone-15.png"
                        },
                        new
                        {
                            Id = 2004,
                            ProductId = 1004,
                            Url = "/images/sample/samsung-galaxy-s24.png"
                        },
                        new
                        {
                            Id = 2005,
                            ProductId = 1005,
                            Url = "/images/sample/logitech-mx-master.png"
                        },
                        new
                        {
                            Id = 2006,
                            ProductId = 1006,
                            Url = "/images/sample/keychron-keyboard.png"
                        },
                        new
                        {
                            Id = 2007,
                            ProductId = 1007,
                            Url = "/images/494a097644004c28a34bed10ae03a4ec.png"
                        },
                        new
                        {
                            Id = 2008,
                            ProductId = 1008,
                            Url = "/images/1.png"
                        },
                        new
                        {
                            Id = 2009,
                            ProductId = 1009,
                            Url = "/images/unnamed (2).png"
                        },
                        new
                        {
                            Id = 2010,
                            ProductId = 1010,
                            Url = "/images/unnamed (31).png"
                        },
                        new
                        {
                            Id = 2011,
                            ProductId = 1011,
                            Url = "/images/unnamed (35).png"
                        },
                        new
                        {
                            Id = 2012,
                            ProductId = 1012,
                            Url = "/images/70a9f09bf5634f80a9578de40ac7fa77.png"
                        },
                        new
                        {
                            Id = 2013,
                            ProductId = 1013,
                            Url = "/images/b08427a925554faeb29c454a04004dc2.png"
                        },
                        new
                        {
                            Id = 2014,
                            ProductId = 1014,
                            Url = "/images/unnamed (22).png"
                        },
                        new
                        {
                            Id = 2015,
                            ProductId = 1015,
                            Url = "/images/unnamed (11).png"
                        },
                        new
                        {
                            Id = 2016,
                            ProductId = 1016,
                            Url = "/images/unnamed (24).png"
                        },
                        new
                        {
                            Id = 2017,
                            ProductId = 1017,
                            Url = "/images/unnamed (25).png"
                        },
                        new
                        {
                            Id = 2018,
                            ProductId = 1018,
                            Url = "/images/unnamed (26).png"
                        });
                });

            modelBuilder.Entity("WebCongNghe.Models.Product", b =>
                {
                    b.HasOne("WebCongNghe.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebCongNghe.Models.ProductImage", b =>
                {
                    b.HasOne("WebCongNghe.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebCongNghe.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebCongNghe.Models.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
