// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebCongNghe.Data;

#nullable disable

namespace WebCongNghe.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260527144307_SeedSampleProducts")]
    partial class SeedSampleProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebCongNghe.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Phu kien"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dien thoai"
                        });
                });

            modelBuilder.Entity("WebCongNghe.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            CategoryId = 1,
                            Description = "Laptop gaming cau hinh cao, phu hop demo danh muc laptop hieu nang.",
                            ImageUrl = "/images/sample/laptop-gaming-asus-rog.png",
                            Name = "Laptop Gaming ASUS ROG",
                            Price = 32990000m
                        },
                        new
                        {
                            Id = 1002,
                            CategoryId = 1,
                            Description = "Laptop nhe, thiet ke gon va phu hop nhom nguoi dung van phong, hoc tap.",
                            ImageUrl = "/images/sample/macbook-air-m3.png",
                            Name = "MacBook Air M3",
                            Price = 28990000m
                        },
                        new
                        {
                            Id = 1003,
                            CategoryId = 3,
                            Description = "Dien thoai cao cap voi camera dep va giao dien hien dai cho demo.",
                            ImageUrl = "/images/sample/iphone-15.png",
                            Name = "iPhone 15",
                            Price = 21990000m
                        },
                        new
                        {
                            Id = 1004,
                            CategoryId = 3,
                            Description = "Dien thoai Android flagship, phu hop de demo nhom san pham di dong.",
                            ImageUrl = "/images/sample/samsung-galaxy-s24.png",
                            Name = "Samsung Galaxy S24",
                            Price = 20990000m
                        },
                        new
                        {
                            Id = 1005,
                            CategoryId = 2,
                            Description = "Chuot khong day cao cap, thao tac tot cho nhu cau van phong va sang tao.",
                            ImageUrl = "/images/sample/logitech-mx-master.png",
                            Name = "Chuot Logitech MX Master",
                            Price = 2490000m
                        },
                        new
                        {
                            Id = 1006,
                            CategoryId = 2,
                            Description = "Ban phim co ket noi da che do, hop voi bo san pham phu kien may tinh.",
                            ImageUrl = "/images/sample/keychron-keyboard.png",
                            Name = "Ban phim co Keychron",
                            Price = 2790000m
                        });
                });

            modelBuilder.Entity("WebCongNghe.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 2001,
                            ProductId = 1001,
                            Url = "/images/sample/laptop-gaming-asus-rog.png"
                        },
                        new
                        {
                            Id = 2002,
                            ProductId = 1002,
                            Url = "/images/sample/macbook-air-m3.png"
                        },
                        new
                        {
                            Id = 2003,
                            ProductId = 1003,
                            Url = "/images/sample/iphone-15.png"
                        },
                        new
                        {
                            Id = 2004,
                            ProductId = 1004,
                            Url = "/images/sample/samsung-galaxy-s24.png"
                        },
                        new
                        {
                            Id = 2005,
                            ProductId = 1005,
                            Url = "/images/sample/logitech-mx-master.png"
                        },
                        new
                        {
                            Id = 2006,
                            ProductId = 1006,
                            Url = "/images/sample/keychron-keyboard.png"
                        });
                });

            modelBuilder.Entity("WebCongNghe.Models.Product", b =>
                {
                    b.HasOne("WebCongNghe.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebCongNghe.Models.ProductImage", b =>
                {
                    b.HasOne("WebCongNghe.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebCongNghe.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WebCongNghe.Models.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
